"""
Parity Oracle — NDCB-XAU
=========================
Diffs Python walk-forward trade list vs MT5 Strategy Tester backtest trades.

Identifies:
  1. Trades Python fired that MT5 MISSED  (filter bug / state-machine miss)
  2. Trades MT5 fired that Python did NOT  (spurious fills / algo drift)
  3. Matched trades where entry PRICE diverged > threshold  (slippage / tick model)

Usage:
  python validation_harness/parity_oracle.py  [MT5_REPORT.html]

  If MT5_REPORT.html is omitted it looks for the most recent HTML file in:
    <repo_root>/CLAUDE MT5/XAUUSD/Backtest/5/

  Python trades are generated by running ndcb_xau() on XAUUSD 2017-2025.
"""
import os, sys, re, codecs, glob
from datetime import date, timedelta
import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from harness import load_mt5_csv
from strategy_lib import ndcb_xau

# ── Paths ──────────────────────────────────────────────────────────────────────
REPO_ROOT   = os.path.join(os.path.dirname(__file__), '..')
DATA        = os.path.join(REPO_ROOT, 'data', 'XAUUSD_H1_2013-2025.csv')
BACKTEST5   = os.path.join(REPO_ROOT, '..', '..', '..', '..', 'CLAUDE MT5',
                            'XAUUSD', 'Backtest', '5')

# Parameters that match v1.2 EA defaults
NDCB_PARAMS = dict(
    compression_ratio  = 0.70,
    entry_buffer_atr   = 0.20,
    stop_atr_mult      = 1.00,
    tp_r               = 2.00,
    trail_trigger_r    = 1.50,
    trail_atr_mult     = 1.00,
)

# Match tolerance
DATE_WINDOW_DAYS  = 1     # match trades within ± N days
PRICE_SLIP_THRESH = 2.0   # $ — flag if entry prices differ by more than this


# ─────────────────────────────────────────────────────────────────────────────
# MT5 HTML PARSER
# ─────────────────────────────────────────────────────────────────────────────

def _decode_mt5_html(path: str) -> str:
    """MT5 saves backtest reports as UTF-16 LE. Try both encodings."""
    for enc in ('utf-16', 'utf-16-le', 'utf-8'):
        try:
            with codecs.open(path, 'r', enc) as f:
                return f.read()
        except (UnicodeDecodeError, UnicodeError):
            continue
    with open(path, 'rb') as f:
        raw = f.read()
    return raw.decode('latin-1', errors='replace')


def parse_mt5_html(html_path: str) -> pd.DataFrame:
    """
    Parse MT5 Strategy Tester HTML report and extract closed position list.

    MT5 report has two trade tables:
      1. Orders table  — pending/market orders
      2. Deals table   — actual fills with open+close rows

    We find the "Deals" section and pair In/Out rows to reconstruct
    entry time, direction, entry price, close time, close price, profit.
    """
    txt = _decode_mt5_html(html_path)

    # Strip any null bytes that appear in UTF-16 LE read
    txt = txt.replace('\x00', '')

    # Find all <tr> rows — we'll scan for the deals table
    rows = re.findall(r'<tr[^>]*>(.*?)</tr>', txt, re.DOTALL | re.IGNORECASE)

    # Each cell
    def cells(row_html):
        return [re.sub(r'<[^>]+>', '', c).strip()
                for c in re.findall(r'<td[^>]*>(.*?)</td>', row_html, re.DOTALL | re.IGNORECASE)]

    # Scan rows to find deals section
    # Deals header looks like: Time | Deal | Symbol | Type | Direction | Volume | Price | ...| Profit
    deals_start = None
    for idx, row in enumerate(rows):
        c = cells(row)
        if len(c) >= 7 and 'deal' in ' '.join(c[:4]).lower() and 'profit' in ' '.join(c).lower():
            deals_start = idx + 1
            break

    if deals_start is None:
        # Try alternate: look for rows with "buy" or "sell" and a price column
        print("  [parity] Could not find Deals section header — scanning all rows for trade data")
        deals_start = 0

    # Collect deal rows: we pair "in" rows with "out" rows by position number
    positions = {}   # pos_id -> dict

    for row in rows[deals_start:]:
        c = cells(row)
        if len(c) < 8:
            continue

        # Try to identify columns by pattern:
        # Typical MT5 deals row: Time | Deal# | Pos# | Symbol | Type | Dir | Volume | Price | SL | TP | Profit | ...
        # Or simpler: Time | Deal# | Symbol | Type | Dir | Volume | Price | Profit

        time_str = c[0]
        if not re.match(r'\d{4}\.\d{2}\.\d{2}', time_str):
            continue

        # Find "buy"/"sell" in row
        row_lower = row.lower()
        if 'buy' not in row_lower and 'sell' not in row_lower:
            continue

        direction_str = ''
        type_str      = ''
        price_str     = ''
        profit_str    = ''
        pos_id        = ''

        # Heuristic column scan
        for i, val in enumerate(c):
            vl = val.lower().strip()
            if vl in ('buy', 'sell'):
                direction_str = vl
            elif vl in ('in', 'out', 'in/out'):
                type_str = vl
            elif re.match(r'^\d+$', val) and not pos_id and i > 0:
                pos_id = val
            elif re.match(r'^\d{1,4}\.\d{2,5}$', val.replace(',', '')) and not price_str:
                price_str = val.replace(',', '')
            elif re.match(r'^-?\d+\.\d{2}$', val.replace(',', '')) and not profit_str:
                profit_str = val.replace(',', '')

        if not direction_str or not price_str:
            continue

        try:
            open_time = pd.to_datetime(time_str, format='%Y.%m.%d %H:%M:%S', errors='coerce')
            if pd.isna(open_time):
                open_time = pd.to_datetime(time_str, dayfirst=False, errors='coerce')
            price_val = float(price_str)
        except Exception:
            continue

        if not pos_id:
            pos_id = f'{direction_str}_{time_str}'

        entry = dict(time=open_time, direction=direction_str, price=price_val,
                     profit=float(profit_str) if profit_str else None,
                     type=type_str)

        if pos_id not in positions:
            positions[pos_id] = []
        positions[pos_id].append(entry)

    # Reconstruct trades from In/Out pairs (or just use single entries)
    trades = []
    for pos_id, entries in positions.items():
        if len(entries) == 0:
            continue
        ins  = [e for e in entries if e['type'] in ('in', 'in/out', '')]
        outs = [e for e in entries if e['type'] in ('out', 'in/out')]

        entry_e = ins[0] if ins else entries[0]
        exit_e  = outs[0] if outs else (entries[-1] if len(entries) > 1 else None)

        trades.append({
            'entry_time': entry_e['time'],
            'direction':  1 if entry_e['direction'] == 'buy' else -1,
            'entry_price': entry_e['price'],
            'exit_time':   exit_e['time']  if exit_e else None,
            'exit_price':  exit_e['price'] if exit_e else None,
            'profit':      exit_e['profit'] if exit_e else entry_e['profit'],
        })

    df = pd.DataFrame(trades)
    if df.empty:
        return df

    df['entry_time'] = pd.to_datetime(df['entry_time'])
    df = df.dropna(subset=['entry_time'])
    df = df.sort_values('entry_time').reset_index(drop=True)
    return df


# ─────────────────────────────────────────────────────────────────────────────
# PYTHON TRADE RUNNER
# ─────────────────────────────────────────────────────────────────────────────

def run_python_trades(start: str, end: str) -> pd.DataFrame:
    h1 = load_mt5_csv(DATA).loc[start:end]
    trades = ndcb_xau(h1, **NDCB_PARAMS)
    if not trades:
        return pd.DataFrame()
    rows = []
    for t in trades:
        rows.append({
            'entry_time':  pd.Timestamp(t.entry_time),
            'direction':   t.direction,
            'entry_price': t.entry_price,
            'exit_time':   pd.Timestamp(t.exit_time),
            'exit_price':  t.exit_price,
            'pnl_r':       t.pnl / 100.0,   # NOTIONAL_RISK=100 → R
        })
    return pd.DataFrame(rows).sort_values('entry_time').reset_index(drop=True)


# ─────────────────────────────────────────────────────────────────────────────
# DIFF ENGINE
# ─────────────────────────────────────────────────────────────────────────────

def diff_trades(py_df: pd.DataFrame, mt5_df: pd.DataFrame) -> dict:
    """
    Align Python vs MT5 trades by entry_date + direction.
    Window: trades within DATE_WINDOW_DAYS of each other, same direction → matched.
    """
    if py_df.empty and mt5_df.empty:
        return dict(matched=[], py_only=[], mt5_only=[], price_divergent=[])

    matched       = []
    py_only       = []
    mt5_only_list = []
    price_divergent = []

    py_used  = set()
    mt5_used = set()

    for pi, pr in py_df.iterrows():
        best_mi, best_gap = None, timedelta(days=DATE_WINDOW_DAYS + 1)
        for mi, mr in mt5_df.iterrows():
            if mi in mt5_used:
                continue
            if mr['direction'] != pr['direction']:
                continue
            gap = abs(pr['entry_time'] - mr['entry_time'])
            if gap < best_gap:
                best_gap, best_mi = gap, mi
        if best_mi is not None and best_gap <= timedelta(days=DATE_WINDOW_DAYS):
            mr = mt5_df.loc[best_mi]
            price_diff = abs(pr['entry_price'] - mr['entry_price'])
            rec = dict(
                py_time=pr['entry_time'], mt5_time=mr['entry_time'],
                direction=pr['direction'],
                py_price=pr['entry_price'], mt5_price=mr['entry_price'],
                price_diff=price_diff,
                time_diff_hours=best_gap.total_seconds() / 3600,
            )
            matched.append(rec)
            py_used.add(pi)
            mt5_used.add(best_mi)
            if price_diff > PRICE_SLIP_THRESH:
                price_divergent.append(rec)
        else:
            py_only.append(pi)

    for mi in mt5_df.index:
        if mi not in mt5_used:
            mt5_only_list.append(mi)

    return dict(
        matched=matched,
        py_only=[py_df.loc[i] for i in py_only],
        mt5_only=[mt5_df.loc[i] for i in mt5_only_list],
        price_divergent=price_divergent,
    )


# ─────────────────────────────────────────────────────────────────────────────
# REPORT
# ─────────────────────────────────────────────────────────────────────────────

def report(diff: dict, py_df: pd.DataFrame, mt5_df: pd.DataFrame):
    matched  = diff['matched']
    py_only  = diff['py_only']
    mt5_only = diff['mt5_only']
    divg     = diff['price_divergent']

    print('\n' + '═' * 72)
    print('  NDCB-XAU PARITY ORACLE')
    print('═' * 72)
    print(f'\n  Python trades:  {len(py_df):>4}')
    print(f'  MT5    trades:  {len(mt5_df):>4}')
    print(f'\n  Matched:        {len(matched):>4}  (both sides fired, aligned by date+dir)')
    print(f'  Python-only:    {len(py_only):>4}  (MT5 MISSED these)')
    print(f'  MT5-only:       {len(mt5_only):>4}  (Python did NOT fire these)')
    print(f'  Price divergent:{len(divg):>4}  (matched but entry price differs > ${PRICE_SLIP_THRESH})')

    if matched:
        diffs = [r['price_diff'] for r in matched]
        print(f'\n  Entry price diff (matched):  '
              f'mean=${np.mean(diffs):.2f}  median=${np.median(diffs):.2f}  '
              f'max=${np.max(diffs):.2f}')
        wfrac = (len(matched) / max(len(py_df), len(mt5_df), 1)) * 100
        print(f'  Match rate: {wfrac:.1f}%')

    # ── Python-only (MT5 missed) ───────────────────────────────────────────
    if py_only:
        print(f'\n  ── PYTHON-ONLY (MT5 missed {len(py_only)} trades) ──')
        for r in py_only[:20]:
            dir_s = 'L' if r['direction'] == 1 else 'S'
            print(f'     {r["entry_time"].strftime("%Y-%m-%d %H:%M")}  {dir_s}  '
                  f'@ {r["entry_price"]:.2f}  PnL={r["pnl_r"]:+.2f}R')
        if len(py_only) > 20:
            print(f'     ... and {len(py_only) - 20} more')

    # ── MT5-only (Python missed) ───────────────────────────────────────────
    if mt5_only:
        print(f'\n  ── MT5-ONLY (Python missed {len(mt5_only)} trades) ──')
        for r in mt5_only[:20]:
            dir_s = 'L' if r['direction'] == 1 else 'S'
            pnl_s = f'{r["profit"]:+.2f}' if r['profit'] is not None else '?'
            print(f'     {r["entry_time"].strftime("%Y-%m-%d %H:%M")}  {dir_s}  '
                  f'@ {r["entry_price"]:.2f}  profit=${pnl_s}')
        if len(mt5_only) > 20:
            print(f'     ... and {len(mt5_only) - 20} more')

    # ── Price divergent ────────────────────────────────────────────────────
    if divg:
        print(f'\n  ── PRICE DIVERGENT (entry differs > ${PRICE_SLIP_THRESH}) ──')
        for r in divg[:15]:
            dir_s = 'L' if r['direction'] == 1 else 'S'
            print(f'     {r["py_time"].strftime("%Y-%m-%d")}  {dir_s}  '
                  f'PY={r["py_price"]:.2f}  MT5={r["mt5_price"]:.2f}  '
                  f'diff=${r["price_diff"]:.2f}')

    print('\n' + '═' * 72)

    # ── Root cause diagnosis ───────────────────────────────────────────────
    miss_rate = len(py_only) / max(len(py_df), 1)
    extra_rate = len(mt5_only) / max(len(mt5_df), 1)

    print('\n  DIAGNOSIS:')
    if miss_rate > 0.20:
        print(f'  ⚠ MT5 missed {miss_rate*100:.0f}% of Python trades — '
              'likely state-machine or bar-close trigger bug in EA')
    if extra_rate > 0.20:
        print(f'  ⚠ MT5 fired {extra_rate*100:.0f}% spurious trades — '
              'filter logic differs between Python and EA')
    if matched and np.mean([r["price_diff"] for r in matched]) > 1.0:
        print('  ⚠ Mean entry price diff > $1 — tick model discrepancy (synthetic M1 OHLC)')
    if miss_rate < 0.10 and extra_rate < 0.10:
        print('  ✓ Good parity — EA faithfully reproduces Python logic')
    print()


# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

def find_latest_html():
    candidates = glob.glob(os.path.join(BACKTEST5, '*.html'))
    if not candidates:
        # Walk up and search broadly
        for root, dirs, files in os.walk(os.path.join(REPO_ROOT, '..', '..', '..', '..')):
            for f in files:
                if 'ReportTester' in f and f.endswith('.html'):
                    candidates.append(os.path.join(root, f))
    if not candidates:
        return None
    return sorted(candidates, key=os.path.getmtime)[-1]


def main():
    html_path = sys.argv[1] if len(sys.argv) > 1 else find_latest_html()

    print(f'\n  MT5 report: {html_path}')
    if not html_path or not os.path.exists(html_path):
        print('\n  ERROR: MT5 HTML report not found.')
        print('  Run the NDCB_XAU_v1_2 backtest in MT5, save the report, then re-run.')
        print('  Or pass the path explicitly:')
        print('    python validation_harness/parity_oracle.py path/to/ReportTester.html')
        sys.exit(1)

    # ── Parse MT5 trades ──────────────────────────────────────────────────
    print('  Parsing MT5 HTML report...')
    mt5_df = parse_mt5_html(html_path)
    print(f'  Parsed {len(mt5_df)} MT5 trades')

    if mt5_df.empty:
        print('\n  WARNING: No trades extracted from MT5 report.')
        print('  The HTML parser may need tuning for this MT5 build version.')
        mt5_start, mt5_end = '2017-01-01', '2025-01-31'
    else:
        mt5_start = mt5_df['entry_time'].min().strftime('%Y-%m-%d')
        mt5_end   = mt5_df['entry_time'].max().strftime('%Y-%m-%d')
        print(f'  MT5 period: {mt5_start} → {mt5_end}')

    # ── Run Python trades on same period ──────────────────────────────────
    print(f'  Running Python ndcb_xau() on {mt5_start} → {mt5_end}...')
    py_df = run_python_trades(mt5_start, mt5_end)
    print(f'  Python fired {len(py_df)} trades')

    # ── Diff ──────────────────────────────────────────────────────────────
    diff = diff_trades(py_df, mt5_df)

    # ── Report ────────────────────────────────────────────────────────────
    report(diff, py_df, mt5_df)

    # ── Save to CSV ───────────────────────────────────────────────────────
    out_dir = os.path.join(REPO_ROOT, 'diagnostic')
    os.makedirs(out_dir, exist_ok=True)

    py_df.to_csv(os.path.join(out_dir, 'parity_python_trades.csv'), index=False)
    if not mt5_df.empty:
        mt5_df.to_csv(os.path.join(out_dir, 'parity_mt5_trades.csv'), index=False)

    if diff['matched']:
        pd.DataFrame(diff['matched']).to_csv(
            os.path.join(out_dir, 'parity_matched.csv'), index=False)

    print(f'  Trade lists saved to: {out_dir}/')


if __name__ == '__main__':
    main()
